name: IDS706_week2-3-assignment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: make install

    - name: Lint with flake8
      run: make lint

    - name: Run tests
      run: ls -R && make test
